"""feat(lead): add lead_requests

Revision ID: 6a47defd100a
Revises: 20260228_0001
Create Date: 2026-03-04 21:41:05.561763
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '6a47defd100a'
down_revision = '20260228_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('profile_slug', sa.String(length=50), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_requests_profile_slug'), 'lead_requests', ['profile_slug'], unique=False)
    op.create_index(op.f('ix_lead_requests_status'), 'lead_requests', ['status'], unique=False)
    op.create_index(op.f('ix_lead_requests_tg_id'), 'lead_requests', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lead_requests_tg_id'), table_name='lead_requests')
    op.drop_index(op.f('ix_lead_requests_status'), table_name='lead_requests')
    op.drop_index(op.f('ix_lead_requests_profile_slug'), table_name='lead_requests')
    op.drop_table('lead_requests')
    # ### end Alembic commands ###
